### ISSUE TITLE
About PFS173 reset pin

### ISSUE THREAD

**Issue by Vanbatai123** [free-pdk/free-pdk-examples#8]
Hi everyone!
I have an issue that how to configure pin A5 as a PRSTB reset pin, i have read datasheet and try it like this but did not work.

uint8_t _sdcc_external_startup(void)
{
	PAC &= ~(1<<5);
	CLKMD |= (1<<0);
	EASY_PDK_INIT_SYSCLOCK_8MHZ();		  //use 8MHz sysclock
	EASY_PDK_CALIBRATE_IHRC(F_CPU, 5000); //tune SYSCLK to 8MHz @ 4.000V
	return 0;							  //perform normal initialization
}
thank in advance.

**Comment by serisman** [comment]
My guess is that EASY_PDK_INIT_SYSCLOCK_8MHZ() is overwriting CLKMD.PA5_PRSTB back to 0, thereby disabling the reset flag.  Try moving `CLKMD |= (1<<0);` to right before `return 0;`.
